### ISSUE TITLE
デザイン２パターンの方針決め

### ISSUE THREAD

**Issue by TatsuyaTonomo** [KSKAnalyticsInc/milestone#1]
TOPページに置こうと思っている各メニューとWORKS画像の構成案を２パターン作って比較したいと思います。

**TODO**
- [ ] パターンA
- [ ] パターンB

**Comment by AkitoshiKitada** [comment]
マークダウンは**Previewタグ**で確認できます。

**Comment by AkitoshiKitada** [comment]
WORKS画像の閲覧方法は縦にスクロールするタイプと、１枚をスライドショー風に大きく見せる２つのタイプがあると良いと思います！

**Comment by TatsuyaTonomo** [comment]
それなら各メニューは縦スクロールなら上部に小さく、横スライドショーなら下部に大きく並べてみてはどうでしょう？？

**Comment by AkitoshiKitada** [comment]
ヘッダーとフッターはどうしましょうか？

**Comment by TatsuyaTonomo** [comment]
とりあえずヘッダーには弊社ログを入れておいて、フッターは縦スクロールにだけ入れれば問題ないと思います。

**Comment by AkitoshiKitada** [comment]
そうですね。横スライドショーさせる方は、WORKSの画像をなるべく大きく見せるためにフッターは削ってみるのが良いと思います！
